image:
  repository: ""
  tag: latest
  pullSecretName: ""

app:
  name: ses-imap
  secretName: ses-imap
  domain: ""
  replicas: 1
  port: 143
  healthPort: 8080

aws:
  region: us-east-1

ingress:
  entryPoint: imaps
  clusterIssuer: letsencrypt-prod

config:
  dynamodbTable: ses-imap-messages
  s3Bucket: ""
  defaultMailbox: INBOX
  ssmPrefix: /ses-imap/users
  ssmCacheTTL: "300"
  logLevel: info
