apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecretName }}
      containers:
      - name: imap-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.app.port }}
          protocol: TCP
        - containerPort: {{ .Values.app.healthPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.app.healthPort }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.app.healthPort }}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secretName }}
              key: aws-access-key
        - name: AWS_REGION
          value: {{ .Values.aws.region | quote }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secretName }}
              key: aws-secret-key
        - name: DEFAULT_MAILBOX
          value: {{ .Values.config.defaultMailbox | quote }}
        - name: DYNAMODB_TABLE
          value: {{ .Values.config.dynamodbTable | quote }}
        - name: IMAP_ADDR
          value: ":{{ .Values.app.port }}"
        - name: LOG_LEVEL
          value: {{ .Values.config.logLevel | quote }}
        - name: S3_BUCKET
          value: {{ .Values.config.s3Bucket | quote }}
        - name: SSM_CACHE_TTL
          value: {{ .Values.config.ssmCacheTTL | quote }}
        - name: SSM_PREFIX
          value: {{ .Values.config.ssmPrefix | quote }}
      restartPolicy: Always
